- name: Download and install telegraf apt public signing key | Debian
  apt_key:
    url:   "{{ telegraf_signing_key_url }}"
    state: present

- name: Add InfluxData repository file | Debian
  apt_repository:
    repo:         "{{ telegraf_apt_repo }}"
    update_cache: yes
    state:        present

- name: Install telegraf | Debian
  apt:
    name: telegraf
    state: present
