---
#ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q ubuntu@54.92.203.55"'

telegraf_global_tags:
    env: "{{ ec2_tag_env }}"
    role: "{{ ec2_tag_role }}"
    title: "{{ ec2_tag_title }}"
    ip: "{{ ec2_ip_address }}"
    type: "{{ ec2_instance_type }}"

telegraf_agent:
    interval: "10s"
    round_interval: true
    metric_batch_size: 1000
    metric_buffer_limit: 10000
    collection_jitter: "0s"
    flush_interval: "10s"
    flush_jitter: "0s"
    debug: false
    quiet: false
    hostname: ""
    omit_hostname: true

telegraf_outputs:     # e.g. influxdb, cloudwatch, amon etc
  - name: influxdb
    urls: ["https://hillvalley-aea42fa3.influxcloud.net:8086"]
    database: "rise" # required
    username: "riser"
    password: "aXvSxSVa5HOzqLs9W2FT5801Cb48w4NcTem7XxeGvYE"
    retention_policy: "default"
    precision: "s"
    timeout: "5s"

telegraf_default_inputs:
  - name: cpu
    percpu: true
    totalcpu: true
    fielddrop: ["time_*"]
  - name: disk
    ignore_fs: ["tmpfs", "devtmpfs"]
  - name: diskio
  - name: kernel
  - name: mem
  - name: net
  - name: ntpq
  - name: processes
  - name: swap
  - name: system
    fielddrop: ["uptime_format"]
